# ----------------------------------------------------
# Configuration du Service (TP1)
# ----------------------------------------------------
spring.application.name=notification-service
server.port=8084 

# ----------------------------------------------------
# Configuration de RabbitMQ (TP5)
# ----------------------------------------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest