# ----------------------------------------------------
# Configuration du Service (TP1)
# ----------------------------------------------------
spring.application.name=notification-service
server.port=8084

# ----------------------------------------------------
# Configuration de RabbitMQ (TP5)
# ----------------------------------------------------
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Eureka Client config
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/