# ----------------------------------------------------
# Configuration du Service (TP1)
# ----------------------------------------------------
spring.application.name=api-gateway 
server.port=8888 

# ----------------------------------------------------
# Configuration d'Eureka Client (TP3)
# ----------------------------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ 
eureka.client.register-with-eureka=true 
eureka.client.fetch-registry=true

# ----------------------------------------------------
# Configuration de Spring Cloud Gateway (TP3)
# ----------------------------------------------------
spring.cloud.gateway.discovery.locator.enabled=true
# Permet de router en utilisant l'ID du service en minuscules (ex: doctor-service)
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Configuration Manuelle de Route (Exemple)
# spring.cloud.gateway.routes[0].id=doctor_route
# spring.cloud.gateway.routes[0].uri=lb://DOCTOR-SERVICE
# spring.cloud.gateway.routes[0].predicates[0]=Path=/api/doctors/**
# Ce bloc est généralement *optionnel* si vous utilisez le Discovery Locator ci-dessus.