# ----------------------------------------------------
# Configuration du Service et du Port (TP1 & TP3)
# ----------------------------------------------------
spring.application.name=doctor-service 
server.port=8082 

# ----------------------------------------------------
# Configuration d'Eureka Client (TP3)
# ----------------------------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/ 
eureka.client.register-with-eureka=true 
eureka.client.fetch-registry=true

# ----------------------------------------------------
# Configuration de la Base de Données PostgreSQL (TP2)
# ----------------------------------------------------
# URL de connexion : port 5432 et base de données 'doctor_db'
spring.datasource.url=jdbc:postgresql://localhost:5432/doctor_db
# Driver
spring.datasource.driver-class-name=org.postgresql.Driver
# Vos identifiants PostgreSQL
spring.datasource.username=postgres 
spring.datasource.password=votre_mot_de_passe_postgres 

# Configuration de Hibernate
spring.jpa.hibernate.ddl-auto=create # Crée ou met à jour les tables à chaque démarrage
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true



