## Fichier : application.properties

# Nom de l'application
spring.application.name=discovery-server

# Port du serveur Eureka
server.port=8761

# Configuration du client Eureka : Indique que ce n'est PAS un client ordinaire.
# 1. Ne s'enregistre pas dans la découverte (car c'est le serveur !)
eureka.client.register-with-eureka=false

# 2. Ne récupère pas la liste des services d'un pair (car c'est le seul serveur !)
eureka.client.fetch-registry=false

# 3. Définit l'URL pour que les clients se connectent (pointe vers lui-même)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
